# Generated by Django 5.2.14 on 2026-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=20, unique=True)),
                ('ultimo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'estado de sincronização',
                'verbose_name_plural': 'estados de sincronização',
            },
        ),
    ]
