"""Catálogo de marcas e modelos de viaturas (dados de referência).

Lista alargada de marcas e modelos vendidos/assistidos em Portugal — atuais,
recentes e **descontinuados** (uma oficina assiste carros com 15-20 anos), mais
quadriciclos (Aixam/Ligier/Microcar) e os novos construtores a entrar no mercado.
Tudo local/offline — não depende de nenhuma API externa.

Usado por `seed_catalogo` (idempotente: get_or_create) e por `seed_demo`.
Para acrescentar: edita o dicionário e corre `python manage.py seed_catalogo`.
"""

CATALOGO = {
    'Abarth': ['500', '595', '695', '124 Spider', '500e', '600e', 'Grande Punto', 'Punto Evo'],
    'Aixam': ['City', 'Crossline', 'Coupé', 'GTO', 'Minauto', 'Crossover', 'e-Aixam'],
    'Alfa Romeo': ['33', '145', '146', '147', '155', '156', '159', '164', '166', 'Brera', 'GT', 'GTV',
                   'Spider', 'MiTo', 'Giulietta', 'Giulia', 'Stelvio', 'Tonale', '4C', '8C', 'Junior'],
    'Aston Martin': ['Vantage', 'DB7', 'DB9', 'DB11', 'DB12', 'DBS', 'DBX', 'Rapide', 'Vanquish', 'Virage'],
    'Audi': ['A1', 'A2', 'A3', 'A4', 'A4 Allroad', 'A5', 'A6', 'A6 Allroad', 'A7', 'A8', '80', '100',
             'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q6 e-tron', 'Q7', 'Q8', 'TT', 'R8',
             'e-tron', 'e-tron GT', 'Cabriolet', 'Coupé'],
    'Bentley': ['Continental GT', 'Flying Spur', 'Bentayga', 'Arnage', 'Azure', 'Mulsanne'],
    'BMW': ['Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'Série 6', 'Série 7', 'Série 8',
            'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z3', 'Z4',
            'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX1', 'iX3', 'M2', 'M3', 'M4', 'M5'],
    'BYD': ['Atto 3', 'Dolphin', 'Dolphin Surf', 'Seal', 'Seal U', 'Han', 'Tang'],
    'Cadillac': ['BLS', 'CTS', 'SRX', 'Escalade'],
    'Chevrolet': ['Spark', 'Matiz', 'Aveo', 'Kalos', 'Cruze', 'Lacetti', 'Nubira', 'Epica', 'Tacuma',
                  'Captiva', 'Orlando', 'Trax', 'Camaro', 'Corvette', 'Volt'],
    'Chrysler': ['300C', '300M', 'Voyager', 'Grand Voyager', 'PT Cruiser', 'Sebring', 'Crossfire', 'Neon'],
    'Citroën': ['2CV', 'AX', 'Saxo', 'ZX', 'BX', 'Xantia', 'Xsara', 'Xsara Picasso',
                'C1', 'C2', 'C3', 'C3 Picasso', 'C3 Aircross', 'C3 Pluriel',
                'C4', 'C4 Picasso', 'Grand C4 Picasso', 'C4 Cactus', 'C4 SpaceTourer', 'C4 X',
                'C5', 'C5 Aircross', 'C5 X', 'C6', 'C8', 'C-Elysée',
                'Berlingo', 'Nemo', 'Jumpy', 'Jumper', 'ë-C4', 'DS3', 'DS4', 'DS5'],
    'Cupra': ['Leon', 'Formentor', 'Born', 'Ateca', 'Tavascan', 'Terramar'],
    'Dacia': ['Sandero', 'Sandero Stepway', 'Logan', 'Logan MCV', 'Duster', 'Jogger', 'Spring',
              'Lodgy', 'Dokker', 'Bigster'],
    'Daewoo': ['Matiz', 'Lanos', 'Nubira', 'Leganza', 'Kalos', 'Tacuma', 'Nexia', 'Espero'],
    'Daihatsu': ['Cuore', 'Sirion', 'Terios', 'Materia', 'Charade', 'Copen', 'YRV', 'Trevis', 'Gran Move'],
    'Dodge': ['Caliber', 'Journey', 'Nitro', 'Avenger', 'RAM'],
    'DS': ['DS 3', 'DS 3 Crossback', 'DS 4', 'DS 7', 'DS 7 Crossback', 'DS 9'],
    'Ferrari': ['California', '458', '488', 'F8 Tributo', '296 GTB', 'Roma', 'Portofino', 'SF90',
                '812', 'Purosangue', '599', 'FF', 'GTC4Lusso'],
    'Fiat': ['500', '500L', '500X', '500e', '600', 'Panda', 'Punto', 'Grande Punto', 'Punto Evo',
             'Tipo', 'Bravo', 'Brava', 'Stilo', 'Marea', 'Multipla', 'Croma', 'Sedici', 'Idea', 'Linea',
             'Doblò', 'Qubo', 'Fiorino', 'Ducato', 'Scudo', 'Ulysse', 'Seicento', 'Cinquecento',
             'Barchetta', 'Coupé', 'Freemont'],
    'Ford': ['Ka', 'Ka+', 'Fiesta', 'Focus', 'Focus C-Max', 'C-Max', 'Grand C-Max', 'Puma', 'EcoSport',
             'Kuga', 'Escort', 'Orion', 'Sierra', 'Mondeo', 'Fusion', 'B-Max', 'S-Max', 'Galaxy',
             'Cougar', 'Probe', 'Capri', 'Scorpio', 'Maverick', 'Edge', 'Explorer', 'Ranger',
             'Transit', 'Transit Custom', 'Transit Connect', 'Tourneo', 'Tourneo Connect',
             'Tourneo Courier', 'Mustang', 'Mustang Mach-E'],
    'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
    'Honda': ['Jazz', 'Civic', 'Civic Type R', 'Accord', 'Insight', 'CR-Z', 'HR-V', 'CR-V', 'ZR-V',
              'FR-V', 'Stream', 'Concerto', 'Prelude', 'Legend', 'S2000', 'NSX', 'e', 'e:Ny1', 'City'],
    'Hyundai': ['Atos', 'Getz', 'i10', 'i20', 'i30', 'i30 N', 'i40', 'Accent', 'Matrix', 'Coupé',
                'Sonata', 'Elantra', 'Bayon', 'Kona', 'ix20', 'ix35', 'ix55', 'Tucson', 'Santa Fe',
                'Terracan', 'Veloster', 'IONIQ', 'IONIQ 5', 'IONIQ 6', 'Staria', 'H-1'],
    'Infiniti': ['Q30', 'Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX70', 'FX', 'EX', 'G37'],
    'Isuzu': ['D-Max', 'Trooper', 'Rodeo'],
    'Iveco': ['Daily'],
    'Jaguar': ['XE', 'XF', 'XJ', 'XK', 'S-Type', 'X-Type', 'E-Pace', 'F-Pace', 'I-Pace', 'F-Type'],
    'Jaecoo': ['7'],
    'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Avenger', 'Patriot',
             'Commander', 'Wagoneer'],
    'Kia': ['Pride', 'Picanto', 'Rio', 'Sephia', 'Ceed', 'ProCeed', 'XCeed', 'Stonic', 'Venga', 'Soul',
            'Niro', 'Stinger', 'Carens', 'Carnival', 'Cerato', 'Magentis', 'Optima', 'Sportage',
            'Sorento', 'EV6', 'EV9'],
    'Lada': ['Niva', 'Niva Legend', 'Riva', 'Samara', '110', 'Kalina', 'Granta', 'Vesta'],
    'Lamborghini': ['Gallardo', 'Murciélago', 'Huracán', 'Aventador', 'Urus', 'Revuelto'],
    'Lancia': ['Ypsilon', 'Delta', 'Musa', 'Lybra', 'Thesis', 'Kappa', 'Phedra', 'Thema', 'Z', 'Voyager'],
    'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport',
                   'Range Rover Evoque', 'Range Rover Velar', 'Freelander', 'Series'],
    'Leapmotor': ['T03', 'C10'],
    'Lexus': ['CT', 'IS', 'ES', 'GS', 'LS', 'UX', 'NX', 'RX', 'RZ', 'RC', 'LC', 'LBX'],
    'Ligier': ['JS50', 'JS60', 'Myli', 'X-Too'],
    'Lynk & Co': ['01', '02', '03', '05', '06', '09'],
    'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'GranCabrio', 'Grecale', 'MC20',
                 'Coupé', 'Spyder'],
    'Maxus': ['Deliver 9', 'eDeliver 3', 'eDeliver 9', 'T90', 'MIFA 9', 'Euniq'],
    'Mazda': ['121', '2', '3', '6', '323', '626', 'MX-3', 'MX-5', 'MX-6', 'MX-30', 'RX-7', 'RX-8',
              'Premacy', 'Tribute', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-7', 'CX-9', 'BT-50', '5',
              'MPV', 'Xedos'],
    'Mercedes-Benz': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'Classe S', 'CLA', 'CLC', 'CLK',
                      'CLS', 'SLK', 'SLC', 'SL', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'GLK', 'ML', 'GL',
                      'R-Class', 'Classe G', 'Classe V', 'Vito', 'Viano', 'Vaneo', 'Citan', 'Sprinter',
                      '190', 'AMG GT', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'EQV'],
    'MG': ['MG3', 'ZR', 'ZS', 'ZS EV', 'ZT', 'TF', 'F', 'MG4', 'MG5', 'MG6', 'MG7', 'HS', 'Marvel R',
           'Cyberster'],
    'Microcar': ['M.Go', 'Dué'],
    'MINI': ['Cooper', 'One', 'Clubman', 'Countryman', 'Paceman', 'Roadster', 'Coupé', 'Cabrio',
             'Electric', 'Aceman'],
    'Mitsubishi': ['Colt', 'Space Star', 'Carisma', 'Lancer', 'Galant', 'Mirage', 'Attrage', 'ASX',
                   'Eclipse Cross', 'Outlander', 'Grandis', 'Space Wagon', 'Space Runner', 'Pajero',
                   'Pajero Pinin', 'Shogun', 'L200', 'i-MiEV', '3000GT'],
    'Nissan': ['Micra', 'Note', 'Almera', 'Primera', 'Pulsar', 'Tiida', 'Leaf', 'Juke', 'Qashqai',
               'X-Trail', 'Murano', 'Pathfinder', 'Patrol', 'Terrano', 'Ariya', 'Pixo', 'Cube',
               '350Z', '370Z', 'GT-R', 'Navara', 'NV200', 'Townstar', 'Primastar', 'Interstar', 'e-NV200'],
    'Omoda': ['5', '5 EV'],
    'Opel': ['Karl', 'Agila', 'Adam', 'Corsa', 'Corsa-e', 'Astra', 'Astra GTC', 'Tigra', 'Calibra',
             'Vectra', 'Insignia', 'Signum', 'Omega', 'Cascada', 'Crossland', 'Mokka', 'Mokka X',
             'Grandland', 'Antara', 'Frontera', 'Meriva', 'Zafira', 'Combo', 'Vivaro', 'Movano',
             'Ampera', 'Manta'],
    'Ora': ['Funky Cat', '03'],
    'Peugeot': ['106', '107', '108', '205', '206', '207', '208', 'e-208', '2008', 'e-2008', '301',
                '306', '307', '308', '308 SW', '309', '3008', '405', '406', '407', '408', '5008',
                '508', '508 SW', '605', '607', '806', '807', '1007', '4007', '4008', 'RCZ',
                'Partner', 'Partner Tepee', 'Rifter', 'Expert', 'Boxer', 'Bipper'],
    'Polestar': ['1', '2', '3', '4'],
    'Porsche': ['911', '718 Cayman', '718 Boxster', 'Boxster', 'Cayman', 'Panamera', 'Macan',
                'Cayenne', 'Taycan', '924', '928', '944', '968'],
    'Renault': ['Twingo', 'Clio', 'Symbol', 'Captur', 'Mégane', 'Mégane E-Tech', 'Mégane Coupé',
                'Scénic', 'Grand Scénic', 'Modus', 'Grand Modus', 'Kadjar', 'Arkana', 'Austral',
                'Espace', 'Grand Espace', 'Laguna', 'Latitude', 'Fluence', 'Talisman', 'Vel Satis',
                'Avantime', 'Koleos', 'Rafale', 'Kangoo', 'Trafic', 'Master', 'Zoe', 'Twizy', 'Wind',
                '5 E-Tech', '4 E-Tech', 'Symbioz'],
    'Rolls-Royce': ['Ghost', 'Phantom', 'Cullinan', 'Wraith', 'Dawn', 'Spectre'],
    'Rover': ['25', '45', '75', '100', '200', '400', '600', '800', 'Streetwise', 'Metro', 'Montego'],
    'Saab': ['900', '9000', '9-3', '9-5', '9-2X', '9-4X'],
    'Seat': ['Marbella', 'Ibiza', 'Cordoba', 'Leon', 'Leon ST', 'Toledo', 'Exeo', 'Arosa', 'Altea',
             'Altea XL', 'Mii', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Inca', 'Ronda'],
    'Škoda': ['Felicia', 'Favorit', 'Fabia', 'Citigo', 'Scala', 'Rapid', 'Octavia', 'Superb',
              'Roomster', 'Praktik', 'Yeti', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Elroq'],
    'Smart': ['ForTwo', 'ForFour', 'Roadster', 'Crossblade', '#1', '#3'],
    'SsangYong': ['Tivoli', 'Korando', 'Rexton', 'Musso', 'Actyon', 'Kyron', 'Rodius', 'Torres'],
    'Subaru': ['Justy', 'Impreza', 'XV', 'Legacy', 'Outback', 'Forester', 'Levorg', 'Trezia', 'BRZ',
               'WRX', 'Tribeca', 'Solterra'],
    'Suzuki': ['Alto', 'Celerio', 'Ignis', 'Swift', 'Baleno', 'Splash', 'Wagon R', 'Liana', 'SX4',
               'SX4 S-Cross', 'S-Cross', 'Vitara', 'Grand Vitara', 'Jimny', 'Samurai', 'Across',
               'Swace', 'Kizashi'],
    'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X', 'Roadster', 'Cybertruck'],
    'Toyota': ['Aygo', 'Aygo X', 'iQ', 'Yaris', 'Yaris Cross', 'Starlet', 'Auris', 'Corolla',
               'Corolla Verso', 'Avensis', 'Carina', 'C-HR', 'Urban Cruiser', 'RAV4', 'Camry', 'Prius',
               'Verso', 'Previa', 'Picnic', 'Highlander', 'Land Cruiser', 'Hilux', 'Proace',
               'Proace City', 'Supra', 'GT86', 'GR86', 'Celica', 'MR2', 'bZ4X', 'Mirai'],
    'Volkswagen': ['Lupo', 'Fox', 'up!', 'Polo', 'Golf', 'Golf Plus', 'Golf Variant', 'Bora', 'Jetta',
                   'Vento', 'Scirocco', 'Beetle', 'New Beetle', 'Passat', 'Passat CC', 'CC', 'Arteon',
                   'Eos', 'Phaeton', 'T-Cross', 'Taigo', 'T-Roc', 'Tiguan', 'Tiguan Allspace', 'Touareg',
                   'Touran', 'Sharan', 'Caddy', 'Crafter', 'Transporter', 'Amarok',
                   'ID.3', 'ID.4', 'ID.5', 'ID.7', 'ID. Buzz'],
    'Volvo': ['240', '850', '940', '960', 'S40', 'V40', 'V50', 'C30', 'C70', 'S60', 'V60', 'S70',
              'V70', 'S80', 'S90', 'V90', 'XC40', 'XC60', 'XC70', 'XC90', 'EX30', 'EX40', 'EC40',
              'EX90', 'C40'],
    'XPeng': ['G6', 'G9', 'P7'],
}
