"""Catálogo de marcas e modelos de viaturas (dados de referência).

Lista alargada de marcas vendidas/assistidas em Portugal (atuais e recentes),
para dar muita escolha nos formulários. Usado por `seed_catalogo` e `seed_demo`.
"""

CATALOGO = {
    'Abarth': ['500', '595', '695', '124 Spider'],
    'Alfa Romeo': ['MiTo', 'Giulietta', 'Giulia', 'Stelvio', 'Tonale', '147', '156', '159', 'Brera'],
    'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'e-tron', 'Q4 e-tron'],
    'BMW': ['Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'Série 6', 'Série 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'Z4', 'i3', 'iX', 'i4'],
    'BYD': ['Atto 3', 'Dolphin', 'Seal', 'Han', 'Tang'],
    'Chevrolet': ['Spark', 'Aveo', 'Cruze', 'Captiva', 'Orlando'],
    'Chrysler': ['300C', 'Voyager', 'PT Cruiser'],
    'Citroën': ['C1', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C5', 'C5 Aircross', 'C5 X', 'Berlingo', 'C-Elysée', 'DS3'],
    'Cupra': ['Leon', 'Formentor', 'Born', 'Ateca', 'Tavascan'],
    'Dacia': ['Sandero', 'Sandero Stepway', 'Logan', 'Duster', 'Jogger', 'Spring', 'Lodgy', 'Dokker'],
    'DS': ['DS 3', 'DS 3 Crossback', 'DS 4', 'DS 7', 'DS 9'],
    'Fiat': ['500', '500L', '500X', 'Panda', 'Punto', 'Tipo', 'Doblò', 'Qubo', '600'],
    'Ford': ['Ka', 'Fiesta', 'Focus', 'Puma', 'Kuga', 'EcoSport', 'Mondeo', 'C-Max', 'S-Max', 'Galaxy', 'Transit', 'Transit Custom', 'Ranger', 'Mustang'],
    'Honda': ['Jazz', 'Civic', 'Accord', 'HR-V', 'CR-V', 'e'],
    'Hyundai': ['i10', 'i20', 'i30', 'i40', 'Bayon', 'Kona', 'Tucson', 'Santa Fe', 'IONIQ', 'IONIQ 5', 'IONIQ 6'],
    'Jaguar': ['XE', 'XF', 'E-Pace', 'F-Pace', 'I-Pace', 'F-Type'],
    'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Avenger'],
    'Kia': ['Picanto', 'Rio', 'Ceed', 'Stonic', 'XCeed', 'Niro', 'Sportage', 'Sorento', 'EV6', 'Soul'],
    'Lancia': ['Ypsilon', 'Delta', 'Musa'],
    'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Freelander'],
    'Lexus': ['CT', 'IS', 'ES', 'UX', 'NX', 'RX'],
    'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'MX-5', 'MX-30'],
    'Mercedes-Benz': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'Classe S', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Classe V', 'Vito', 'Sprinter', 'EQA', 'EQB', 'EQC'],
    'MG': ['MG3', 'ZS', 'ZS EV', 'HS', 'MG4', 'MG5', 'Marvel R'],
    'MINI': ['Cooper', 'One', 'Clubman', 'Countryman', 'Cabrio', 'Electric'],
    'Mitsubishi': ['Space Star', 'ASX', 'Eclipse Cross', 'Outlander', 'L200'],
    'Nissan': ['Micra', 'Note', 'Leaf', 'Juke', 'Qashqai', 'X-Trail', 'Ariya', 'Navara'],
    'Opel': ['Karl', 'Corsa', 'Astra', 'Insignia', 'Adam', 'Crossland', 'Mokka', 'Grandland', 'Combo', 'Vivaro', 'Zafira'],
    'Peugeot': ['108', '208', '2008', '301', '308', '3008', '408', '508', '5008', 'Partner', 'Rifter', 'Expert', 'Boxer'],
    'Porsche': ['911', '718 Cayman', '718 Boxster', 'Panamera', 'Macan', 'Cayenne', 'Taycan'],
    'Renault': ['Twingo', 'Clio', 'Captur', 'Mégane', 'Mégane E-Tech', 'Scénic', 'Kadjar', 'Arkana', 'Austral', 'Kangoo', 'Trafic', 'Master', 'Zoe', 'Espace'],
    'Saab': ['9-3', '9-5'],
    'Seat': ['Mii', 'Ibiza', 'Leon', 'Toledo', 'Arona', 'Ateca', 'Tarraco', 'Alhambra'],
    'Škoda': ['Citigo', 'Fabia', 'Scala', 'Rapid', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Roomster', 'Yeti'],
    'Smart': ['ForTwo', 'ForFour', '#1', '#3'],
    'SsangYong': ['Tivoli', 'Korando', 'Rexton', 'Musso'],
    'Subaru': ['Impreza', 'XV', 'Forester', 'Outback', 'Levorg'],
    'Suzuki': ['Ignis', 'Swift', 'Baleno', 'Vitara', 'S-Cross', 'Jimny', 'Across'],
    'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X'],
    'Toyota': ['Aygo', 'Aygo X', 'Yaris', 'Yaris Cross', 'Corolla', 'C-HR', 'RAV4', 'Camry', 'Prius', 'Highlander', 'Land Cruiser', 'Hilux', 'Proace'],
    'Volkswagen': ['up!', 'Polo', 'Golf', 'Golf Variant', 'Jetta', 'Passat', 'Arteon', 'T-Cross', 'Taigo', 'T-Roc', 'Tiguan', 'Touareg', 'Touran', 'Sharan', 'Caddy', 'Transporter', 'ID.3', 'ID.4', 'ID.5'],
    'Volvo': ['V40', 'S60', 'V60', 'S90', 'V90', 'XC40', 'XC60', 'XC90', 'EX30', 'C40'],
}
