# Generated by Django 5.2.14 on 2026-05-29 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=12, verbose_name='código postal')),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(help_text='Identificador para URLs por loja (futuro).', unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='preço base')),
                ('duracao_estimada', models.DurationField(blank=True, help_text='Para marcações (fase posterior).', null=True, verbose_name='duração estimada')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, help_text='Periodicidade em km (vazio = não recorrente).', null=True)),
                ('intervalo_meses', models.PositiveIntegerField(blank=True, help_text='Periodicidade em meses (vazio = não recorrente).', null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de serviço',
                'verbose_name_plural': 'tipos de serviço',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, help_text='Ex.: mecânico, rececionista.', max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='oficina.local')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do serviço')),
                ('quilometragem', models.PositiveIntegerField(blank=True, null=True)),
                ('trabalho_feito', models.TextField(verbose_name='trabalho feito')),
                ('pecas', models.TextField(blank=True, help_text='Peças usadas (texto livre por agora).', verbose_name='peças')),
                ('estado', models.CharField(choices=[('em_execucao', 'Em execução'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='concluido', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('funcionario', models.ForeignKey(blank=True, help_text='Quem executou o serviço.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registos', to='oficina.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos', to='oficina.local')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_criados', to=settings.AUTH_USER_MODEL)),
                ('registo_corrigido', models.ForeignKey(blank=True, help_text='Se preenchido, esta entrada corrige/anula a original (o log é append-only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes', to='oficina.registoservico')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos', to='oficina.tiposervico')),
            ],
            options={
                'verbose_name': 'registo de serviço',
                'verbose_name_plural': 'registos de serviço',
                'ordering': ['-data_servico', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoRegisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='registos/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='oficina.registoservico')),
            ],
            options={
                'verbose_name': 'foto de registo',
                'verbose_name_plural': 'fotos de registo',
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15, unique=True, verbose_name='matrícula')),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('combustivel', models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido'), ('gpl', 'GPL'), ('outro', 'Outro')], max_length=15, verbose_name='combustível')),
                ('cor', models.CharField(blank=True, max_length=40)),
                ('vin', models.CharField(blank=True, max_length=40, verbose_name='VIN / nº de chassis')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='oficina.cliente')),
                ('local', models.ForeignKey(help_text='Oficina de registo da viatura.', on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='oficina.local')),
            ],
            options={
                'verbose_name': 'viatura',
                'verbose_name_plural': 'viaturas',
                'ordering': ['matricula'],
            },
        ),
        migrations.AddField(
            model_name='registoservico',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registos', to='oficina.viatura'),
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='oficina.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes', to='oficina.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='oficina.local')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='oficina.tiposervico')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='oficina.viatura')),
            ],
            options={
                'verbose_name': 'marcação',
                'verbose_name_plural': 'marcações',
                'ordering': ['data_hora'],
            },
        ),
    ]
