# Generated by Django 5.2.14 on 2026-05-29 08:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=60, unique=True, verbose_name='referência')),
                ('nome', models.CharField(max_length=160)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='preço de venda')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'peça',
                'verbose_name_plural': 'peças',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='registoservico',
            name='pecas',
        ),
        migrations.AddField(
            model_name='viatura',
            name='inspecao_valida_ate',
            field=models.DateField(blank=True, help_text='Validade da Inspeção Periódica Obrigatória.', null=True, verbose_name='IPO válida até'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='duracao_estimada',
            field=models.DurationField(blank=True, help_text='Para marcações.', null=True, verbose_name='duração estimada'),
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('quilometragem', models.PositiveIntegerField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('ok', 'Tudo OK'), ('atencao', 'Requer atenção'), ('urgente', 'Intervenção urgente')], default='ok', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='oficina.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='oficina.local')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='oficina.viatura')),
            ],
            options={
                'verbose_name': 'inspeção',
                'verbose_name_plural': 'inspeções',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('atencao', 'Atenção'), ('urgente', 'Urgente')], default='ok', max_length=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inspecoes/%Y/%m/')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.inspecao')),
            ],
            options={
                'verbose_name': 'ponto de inspeção',
                'verbose_name_plural': 'pontos de inspeção',
            },
        ),
        migrations.AlterField(
            model_name='viatura',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='oficina.marca'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='oficina.marca')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ['marca__nome', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='viatura',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='oficina.modelo'),
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='rascunho', max_length=12)),
                ('validade', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='oficina.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='oficina.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='oficina.local')),
                ('registo_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_origem', to='oficina.registoservico')),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='oficina.tiposervico')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='oficina.viatura')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mao_obra', 'Mão de obra'), ('peca', 'Peça')], default='mao_obra', max_length=10)),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='preço unitário')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.orcamento')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='oficina.peca')),
            ],
            options={
                'verbose_name': 'item de orçamento',
                'verbose_name_plural': 'itens de orçamento',
            },
        ),
        migrations.CreateModel(
            name='PecaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='preço unitário')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='oficina.peca')),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='oficina.registoservico')),
            ],
            options={
                'verbose_name': 'peça do serviço',
                'verbose_name_plural': 'peças do serviço',
            },
        ),
        migrations.CreateModel(
            name='StockPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='oficina.local')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='oficina.peca')),
            ],
            options={
                'verbose_name': 'stock de peça',
                'verbose_name_plural': 'stock de peças',
                'ordering': ['peca__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nome'), name='modelo_unico_por_marca'),
        ),
        migrations.AddConstraint(
            model_name='stockpeca',
            constraint=models.UniqueConstraint(fields=('peca', 'local'), name='stock_unico_peca_local'),
        ),
    ]
