# Generated by Django 5.2.14 on 2026-05-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_marca_peca_remove_registoservico_pecas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='capacidade_slot',
            field=models.PositiveSmallIntegerField(default=2, help_text='Marcações simultâneas possíveis no mesmo horário.', verbose_name='capacidade por horário'),
        ),
    ]
