# Generated by Django 5.2.14 on 2026-05-29 10:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_local_capacidade_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aberta', 'Aberta'), ('em_execucao', 'Em execução'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('quilometragem', models.PositiveIntegerField(blank=True, null=True, verbose_name='quilometragem à entrada')),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='oficina.funcionario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.local')),
                ('marcacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='oficina.marcacao')),
                ('orcamento', models.ForeignKey(blank=True, help_text='Orçamento de referência (para comparar com os extras).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='oficina.orcamento')),
                ('registo_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_origem', to='oficina.registoservico')),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.tiposervico')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.viatura')),
            ],
            options={
                'verbose_name': 'ordem de trabalho',
                'verbose_name_plural': 'ordens de trabalho',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mao_obra', 'Mão de obra'), ('peca', 'Peça')], default='peca', max_length=10)),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='preço unitário')),
                ('fora_orcamento', models.BooleanField(default=True, verbose_name='fora do orçamento (extra)')),
                ('nota', models.CharField(blank=True, help_text='Justificação do imprevisto.', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='oficina.peca')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.ordemtrabalho')),
            ],
            options={
                'verbose_name': 'item da ordem',
                'verbose_name_plural': 'itens da ordem',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ordens/%Y/%m/')),
                ('categoria', models.CharField(choices=[('entrada', 'Estado à entrada'), ('imprevisto', 'Imprevisto'), ('durante', 'Durante o trabalho'), ('fim', 'Trabalho concluído')], default='durante', max_length=12)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='oficina.funcionario')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='oficina.itemordem')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='oficina.ordemtrabalho')),
            ],
            options={
                'verbose_name': 'foto da ordem',
                'verbose_name_plural': 'fotos da ordem',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='oficina.funcionario')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='oficina.ordemtrabalho')),
            ],
            options={
                'verbose_name': 'sessão de trabalho',
                'verbose_name_plural': 'sessões de trabalho',
                'ordering': ['inicio'],
            },
        ),
    ]
