# Generated by Django 5.2.14 on 2026-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_ordemtrabalho_itemordem_fotoordem_sessaotrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN de acesso ao tablet (guardado cifrado).', max_length=128, verbose_name='PIN'),
        ),
    ]
