# Generated by Django 5.2.14 on 2026-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_alter_cliente_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoordem',
            name='ficheiro_enviado',
            field=models.BooleanField(default=False, editable=False, verbose_name='ficheiro enviado p/ cloud'),
        ),
        migrations.AddField(
            model_name='fotoregisto',
            name='ficheiro_enviado',
            field=models.BooleanField(default=False, editable=False, verbose_name='ficheiro enviado p/ cloud'),
        ),
    ]
