# Generated by Django 5.2.14 on 2026-05-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficina', '0008_fotoordem_ficheiro_enviado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFaturacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=40, unique=True)),
                ('ultimo', models.DateTimeField(blank=True, null=True, verbose_name='último puxado')),
            ],
            options={
                'verbose_name': 'estado de faturação',
                'verbose_name_plural': 'estados de faturação',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=40, verbose_name='software')),
                ('id_externo', models.CharField(max_length=120, verbose_name='ID no software')),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='número')),
                ('data', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moeda', models.CharField(default='EUR', max_length=3)),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('nome', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pdf', models.FileField(blank=True, upload_to='faturas/', verbose_name='PDF')),
                ('pdf_url', models.URLField(blank=True, max_length=500, verbose_name='URL original')),
                ('estado', models.CharField(choices=[('casada_nif', 'Casada por NIF'), ('casada_email', 'Casada por email'), ('manual', 'Atribuída manualmente'), ('por_resolver', 'Por resolver')], default='por_resolver', max_length=20)),
                ('puxado_em', models.DateTimeField(auto_now_add=True, verbose_name='puxado em')),
                ('cliente', models.ForeignKey(blank=True, help_text='A que cliente pertence. Pode ficar vazio até casar (estado "por resolver").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='oficina.cliente')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-data', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provedor', 'id_externo'), name='fatura_unica_por_provedor')],
            },
        ),
    ]
